<!DOCTYPE html><html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Habron - FLASH/BETA</title><style>#container{
            width: 500px;height: 600px;padding: 20px;background-color: #0072bc;position: absolute;top: 50%;left: 50%;margin-left: -260px;margin-top: -275px;color:rgb(255, 255, 255);box-shadow: rgb(33, 52, 160) 0px 1px 0px 4px ;border-radius: 10px;}h1 {font-family: "Ubuntu Condensed","Trebuchet MS","Lucida Grande","Lucida Sans Unicode","Lucida Sans",Tahoma,sans-serif;text-align: center;}.reayz {width: 400px;object-fit: cover;float: left;position: absolute;right: 250px;bottom: -5px;}
        .flash{background-color: #ffb900;width: auto;height: auto;float: left;border: 2px solid #ffea00;margin-right: 20px;margin-top: 0px;color: #000;font-weight: 500;left: 50px;font-size: 13px;text-align: center;text-transform: uppercase;position: relative;text-decoration: none;
            font-family: sans-serif;z-index: 99999;border-radius: 3px;cursor: pointer; padding: 10px 30px;filter: drop-shadow(-1px 4px 0 rgba(0, 0, 0, .3));line-height: 26px;}.beta{}.flash:hover {opacity: 0.9;}.logo{position: absolute; top: 50%;left: 50%;margin-left: -260px;margin-top: -375px; z-index: 999999;}.sea{ width: 400px;object-fit: cover;float: left;position: absolute;right: 0px;bottom: 0px;opacity: 0.1;}p{float: left;padding:0 10px 10px 0;font-family: sans-serif;}a {line-height: 26px;float: right;position: absolute;color: darkblue;text-decoration: none;font-family: sans-serif;}.rp {float: right;position: absolute;bottom: 0px;width: 100%;left: 260px;color: white;}</style></head><body style="background-color: #000000;"><div><img class="logo" src="https://media.discordapp.net/attachments/690248336355491956/831650526022205500/habronlogo.png?163566738137513243241312111" alt=""></div><div id="container"><h1>Habronu nasıl oynayacağına karar ver!</h1><a class="flash" href="/client">Hotele gir(Flash)</a><a class="flash" href="/beta">Hotele gir(Beta)</a><p>GOOGLE CHROME KULLANICILARI DİKKATİNE! Bildiğiniz üzere 2020 yılında Flash PLayer Kaldırıldı. Bizde HTML5 yapısına geçiş yaptık. Eğer oyunu eski Flash versiyonu ile oynamak istiyorsanız Uygulamamızı indirmeniz gerekiyor. Googleden oynamaya devam etmek için ise Hotele gir(Beta) butonuna basmanız yeterli!</p><img class="reayz" src="https://cdn.discordapp.com/attachments/848614649862553650/868899196965642290/Screenshot_30.png" alt="Reayz"><div>
        <a class="flash" href="/apps">Uygulamayı indirmek için tıkla!<br> Uygulama sayesinde FLASH'a girebilirsin!</a></div> </div>
</body></html>
